# Generated by Django 2.1.7 on 2019-03-18 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zid_code',
            new_name='zip_code',
        ),
    ]
