# Generated by Django 2.1.7 on 2019-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_producttag_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product-thumbnails'),
        ),
    ]
