# Generated by Django 2.1.7 on 2019-03-04 10:18

from django.db import migrations


def capitalize(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190303_2110'),
    ]

    operations = [

        migrations.RunPython(
            capitalize,
            migrations.RunPython.noop
        ),
    ]
